# SPDX-FileCopyrightText: 2025-present Demi <bjaiye1@gmail.com>
#
# SPDX-License-Identifier: MIT
"""TelluriumSBMLBioModule wrapper for Abroudi2017 - Mammalian Cell Cycle Control Model.

Source: biomodels_ebi:MODEL1812130001
Original: https://www.ebi.ac.uk/biomodels/MODEL1812130001
"""
from __future__ import annotations

from typing import Any, Optional

from biosim.contrib.sbml import TelluriumSBMLBioModule


class SbmlAbroudi2017MammalianCellCycleControlModel(TelluriumSBMLBioModule):
    """BioModule wrapper for SBML model: Abroudi2017 - Mammalian Cell Cycle Control Model."""

    _SBML_ID = 'MODEL1812130001'
    _TITLE = 'Abroudi2017 - Mammalian Cell Cycle Control Model'
    _TIME_UNIT = 'model_time'
    _OBSERVABLE_STRATEGY = 'species'
    _OBSERVABLES = [
        'acMyc',
        'icMyc',
        'ATM',
        'aChk2',
        'iChk2',
        'p53',
        'mdm2',
        'IF',
        'p21',
        'cycd_cdk4',
        'p21_cycd_cdk4',
        'acyce_cdk2',
        'p21_acyce_cdk2',
        'p21_acyca_cdk2',
        'acyca_cdk2',
        '_14_3_3_s',
        'gadda45',
        'cycd',
        'cdk4',
        'ascf',
        'p27',
        'p27_acyce_cdk2',
        'p27_acyca_cdk2',
        'E2F',
        'pRb',
        'E2F_pRb',
        'p27_cycd_cdk4',
        'E2F_pRbPP',
        'pRbPPP',
        'app1',
        'ipp1',
        'acycb_cdk1_nuc',
        'cyce',
        'cdk2',
        'cyca',
        'aBMyb',
        'NFY',
        'icyca_cdk2',
        'aAPC_Cdc20',
        'aAPC_Cdh1',
        'icyce_cdk2',
        'acdc25a',
        'iscf',
        'iBMyb',
        'icdc25a',
        'aplk1',
        'awee1',
        'iwee1',
        'acdc25c',
        'icdc25c',
        'icdc25cp_s216',
        'acycb_cdk1_cyto',
        'acdc25cp_s216',
        '_14_3_3_icdc25cp_s216',
        'iplk1',
        'cycb',
        'cdk1',
        'icycb_cdk1_cyto',
        'p21_acycb_cdk1_nuc',
        'icycb_cdk1_nuc',
        'iAPC_Cdc20',
        'iAPC_Cdh1',
        'pRbPPP_copy',
    ]
    _SPECIES_LABELS = {
        'acMyc': 'Active Myc',
        'icMyc': 'Inactive Myc',
        'ATM': 'ATM checkpoint kinase',
        'aChk2': 'Active Chk2',
        'iChk2': 'Inactive Chk2',
        'p53': 'p53 tumor suppressor',
        'mdm2': 'Mdm2',
        'IF': 'Model state IF',
        'p21': 'P21',
        'cycd_cdk4': 'Cyclin D CDK4',
        'p21_cycd_cdk4': 'P21 Cyclin D CDK4',
        'acyce_cdk2': 'Acyce CDK2',
        'p21_acyce_cdk2': 'P21 Acyce CDK2',
        'p21_acyca_cdk2': 'P21 Acyca CDK2',
        'acyca_cdk2': 'Acyca CDK2',
        '_14_3_3_s': '14-3-3 S',
        'gadda45': 'Gadda45',
        'cycd': 'Cyclin D',
        'cdk4': 'CDK4',
        'ascf': 'Ascf',
        'p27': 'p27 CDK inhibitor',
        'p27_acyce_cdk2': 'P27 Acyce CDK2',
        'p27_acyca_cdk2': 'P27 Acyca CDK2',
        'E2F': 'E2F transcription factor',
        'pRb': 'Phosphorylated Rb',
        'E2F_pRb': 'E2F Phosphorylated Rb',
        'p27_cycd_cdk4': 'P27 Cyclin D CDK4',
        'E2F_pRbPP': 'Phosphorylated E2F Phosphorylated Rb P',
        'pRbPPP': 'Phosphorylated Phosphorylated Rb PP',
        'app1': 'App1',
        'ipp1': 'Ipp1',
        'acycb_cdk1_nuc': 'Acycb CDK1 Nuc',
        'cyce': 'Cyclin E',
        'cdk2': 'CDK2',
        'cyca': 'Cyclin A',
        'aBMyb': 'Active BMyb',
        'NFY': 'NF-Y transcription factor',
        'icyca_cdk2': 'Icyca CDK2',
        'aAPC_Cdc20': 'Active APC/C/C Cdc20',
        'aAPC_Cdh1': 'Active APC/C/C Cdh1',
        'icyce_cdk2': 'Icyce CDK2',
        'acdc25a': 'Acdc25a',
        'iscf': 'Iscf',
        'iBMyb': 'Inactive BMyb',
        'icdc25a': 'Icdc25a',
        'aplk1': 'Aplk1',
        'awee1': 'Awee1',
        'iwee1': 'Iwee1',
        'acdc25c': 'Acdc25c',
        'icdc25c': 'Icdc25c',
        'icdc25cp_s216': 'Icdc25cp S216',
        'acycb_cdk1_cyto': 'Acycb CDK1 Cyto',
        'acdc25cp_s216': 'Acdc25cp S216',
        '_14_3_3_icdc25cp_s216': '14-3-3 Icdc25cp S216',
        'iplk1': 'Iplk1',
        'cycb': 'Cyclin B',
        'cdk1': 'CDK1',
        'icycb_cdk1_cyto': 'Icycb CDK1 Cyto',
        'p21_acycb_cdk1_nuc': 'P21 Acycb CDK1 Nuc',
        'icycb_cdk1_nuc': 'Icycb CDK1 Nuc',
        'iAPC_Cdc20': 'Inactive APC/C/C Cdc20',
        'iAPC_Cdh1': 'Inactive APC/C/C Cdh1',
        'pRbPPP_copy': 'Phosphorylated Rb PPP Copy',
    }
    _PARAMETER_INPUTS = {
        'dsb': ('DSB', 0.012, 'native SBML value', 'Controls DSB. Maps to SBML symbol `DSB`.'),
        'oxygen_dependent_degradation_factor': ('DEG', 0.0556, 'native SBML value', 'Controls Oxygen-dependent degradation factor. Maps to SBML symbol `DEG`.'),
        'growth_factor': ('GF', 1.0, 'native SBML value', 'Controls Growth Factor. Maps to SBML symbol `GF`.'),
    }
    _HEADLINE_OUTPUTS = {
        'active_myc': ('acMyc', 'native SBML value', 'Tracks Active Myc. Maps to SBML symbol `acMyc`.'),
        'inactive_myc': ('icMyc', 'native SBML value', 'Tracks Inactive Myc. Maps to SBML symbol `icMyc`.'),
        'atm_checkpoint_kinase': ('ATM', 'native SBML value', 'Tracks ATM checkpoint kinase. Maps to SBML symbol `ATM`.'),
        'active_chk2': ('aChk2', 'native SBML value', 'Tracks Active Chk2. Maps to SBML symbol `aChk2`.'),
        'inactive_chk2': ('iChk2', 'native SBML value', 'Tracks Inactive Chk2. Maps to SBML symbol `iChk2`.'),
        'p53_tumor_suppressor': ('p53', 'native SBML value', 'Tracks p53 tumor suppressor. Maps to SBML symbol `p53`.'),
        'mdm2': ('mdm2', 'native SBML value', 'Tracks Mdm2. Maps to SBML symbol `mdm2`.'),
        'model_state_if': ('IF', 'native SBML value', 'Tracks Model state IF. Maps to SBML symbol `IF`.'),
        'p21': ('p21', 'native SBML value', 'Tracks P21. Maps to SBML symbol `p21`.'),
        'cyclin_d_cdk4': ('cycd_cdk4', 'native SBML value', 'Tracks Cyclin D CDK4. Maps to SBML symbol `cycd_cdk4`.'),
        'p21_cyclin_d_cdk4': ('p21_cycd_cdk4', 'native SBML value', 'Tracks P21 Cyclin D CDK4. Maps to SBML symbol `p21_cycd_cdk4`.'),
        'acyce_cdk2': ('acyce_cdk2', 'native SBML value', 'Tracks Acyce CDK2. Maps to SBML symbol `acyce_cdk2`.'),
        'p21_acyce_cdk2': ('p21_acyce_cdk2', 'native SBML value', 'Tracks P21 Acyce CDK2. Maps to SBML symbol `p21_acyce_cdk2`.'),
        'p21_acyca_cdk2': ('p21_acyca_cdk2', 'native SBML value', 'Tracks P21 Acyca CDK2. Maps to SBML symbol `p21_acyca_cdk2`.'),
        'acyca_cdk2': ('acyca_cdk2', 'native SBML value', 'Tracks Acyca CDK2. Maps to SBML symbol `acyca_cdk2`.'),
        'observable_14_3_3_s': ('_14_3_3_s', 'native SBML value', 'Tracks 14-3-3 S. Maps to SBML symbol `_14_3_3_s`.'),
        'gadda45': ('gadda45', 'native SBML value', 'Tracks Gadda45. Maps to SBML symbol `gadda45`.'),
        'cyclin_d': ('cycd', 'native SBML value', 'Tracks Cyclin D. Maps to SBML symbol `cycd`.'),
        'cdk4': ('cdk4', 'native SBML value', 'Tracks CDK4. Maps to SBML symbol `cdk4`.'),
        'ascf': ('ascf', 'native SBML value', 'Tracks Ascf. Maps to SBML symbol `ascf`.'),
        'p27_cdk_inhibitor': ('p27', 'native SBML value', 'Tracks p27 CDK inhibitor. Maps to SBML symbol `p27`.'),
        'p27_acyce_cdk2': ('p27_acyce_cdk2', 'native SBML value', 'Tracks P27 Acyce CDK2. Maps to SBML symbol `p27_acyce_cdk2`.'),
        'p27_acyca_cdk2': ('p27_acyca_cdk2', 'native SBML value', 'Tracks P27 Acyca CDK2. Maps to SBML symbol `p27_acyca_cdk2`.'),
        'e2f_transcription_factor': ('E2F', 'native SBML value', 'Tracks E2F transcription factor. Maps to SBML symbol `E2F`.'),
        'phosphorylated_rb': ('pRb', 'native SBML value', 'Tracks Phosphorylated Rb. Maps to SBML symbol `pRb`.'),
        'e2f_phosphorylated_rb': ('E2F_pRb', 'native SBML value', 'Tracks E2F Phosphorylated Rb. Maps to SBML symbol `E2F_pRb`.'),
        'p27_cyclin_d_cdk4': ('p27_cycd_cdk4', 'native SBML value', 'Tracks P27 Cyclin D CDK4. Maps to SBML symbol `p27_cycd_cdk4`.'),
        'phosphorylated_e2f_phosphorylated_rb_p': ('E2F_pRbPP', 'native SBML value', 'Tracks Phosphorylated E2F Phosphorylated Rb P. Maps to SBML symbol `E2F_pRbPP`.'),
        'phosphorylated_phosphorylated_rb_pp': ('pRbPPP', 'native SBML value', 'Tracks Phosphorylated Phosphorylated Rb PP. Maps to SBML symbol `pRbPPP`.'),
        'app1': ('app1', 'native SBML value', 'Tracks App1. Maps to SBML symbol `app1`.'),
        'ipp1': ('ipp1', 'native SBML value', 'Tracks Ipp1. Maps to SBML symbol `ipp1`.'),
        'acycb_cdk1_nuc': ('acycb_cdk1_nuc', 'native SBML value', 'Tracks Acycb CDK1 Nuc. Maps to SBML symbol `acycb_cdk1_nuc`.'),
        'cyclin_e': ('cyce', 'native SBML value', 'Tracks Cyclin E. Maps to SBML symbol `cyce`.'),
        'cdk2': ('cdk2', 'native SBML value', 'Tracks CDK2. Maps to SBML symbol `cdk2`.'),
        'cyclin_a': ('cyca', 'native SBML value', 'Tracks Cyclin A. Maps to SBML symbol `cyca`.'),
        'active_bmyb': ('aBMyb', 'native SBML value', 'Tracks Active BMyb. Maps to SBML symbol `aBMyb`.'),
        'nf_y_transcription_factor': ('NFY', 'native SBML value', 'Tracks NF-Y transcription factor. Maps to SBML symbol `NFY`.'),
        'icyca_cdk2': ('icyca_cdk2', 'native SBML value', 'Tracks Icyca CDK2. Maps to SBML symbol `icyca_cdk2`.'),
        'active_apc_c_c_cdc20': ('aAPC_Cdc20', 'native SBML value', 'Tracks Active APC/C/C Cdc20. Maps to SBML symbol `aAPC_Cdc20`.'),
        'active_apc_c_c_cdh1': ('aAPC_Cdh1', 'native SBML value', 'Tracks Active APC/C/C Cdh1. Maps to SBML symbol `aAPC_Cdh1`.'),
        'icyce_cdk2': ('icyce_cdk2', 'native SBML value', 'Tracks Icyce CDK2. Maps to SBML symbol `icyce_cdk2`.'),
        'acdc25a': ('acdc25a', 'native SBML value', 'Tracks Acdc25a. Maps to SBML symbol `acdc25a`.'),
        'iscf': ('iscf', 'native SBML value', 'Tracks Iscf. Maps to SBML symbol `iscf`.'),
        'inactive_bmyb': ('iBMyb', 'native SBML value', 'Tracks Inactive BMyb. Maps to SBML symbol `iBMyb`.'),
        'icdc25a': ('icdc25a', 'native SBML value', 'Tracks Icdc25a. Maps to SBML symbol `icdc25a`.'),
        'aplk1': ('aplk1', 'native SBML value', 'Tracks Aplk1. Maps to SBML symbol `aplk1`.'),
        'awee1': ('awee1', 'native SBML value', 'Tracks Awee1. Maps to SBML symbol `awee1`.'),
        'iwee1': ('iwee1', 'native SBML value', 'Tracks Iwee1. Maps to SBML symbol `iwee1`.'),
        'acdc25c': ('acdc25c', 'native SBML value', 'Tracks Acdc25c. Maps to SBML symbol `acdc25c`.'),
        'icdc25c': ('icdc25c', 'native SBML value', 'Tracks Icdc25c. Maps to SBML symbol `icdc25c`.'),
        'icdc25cp_s216': ('icdc25cp_s216', 'native SBML value', 'Tracks Icdc25cp S216. Maps to SBML symbol `icdc25cp_s216`.'),
        'acycb_cdk1_cyto': ('acycb_cdk1_cyto', 'native SBML value', 'Tracks Acycb CDK1 Cyto. Maps to SBML symbol `acycb_cdk1_cyto`.'),
        'acdc25cp_s216': ('acdc25cp_s216', 'native SBML value', 'Tracks Acdc25cp S216. Maps to SBML symbol `acdc25cp_s216`.'),
        'observable_14_3_3_icdc25cp_s216': ('_14_3_3_icdc25cp_s216', 'native SBML value', 'Tracks 14-3-3 Icdc25cp S216. Maps to SBML symbol `_14_3_3_icdc25cp_s216`.'),
        'iplk1': ('iplk1', 'native SBML value', 'Tracks Iplk1. Maps to SBML symbol `iplk1`.'),
        'cyclin_b': ('cycb', 'native SBML value', 'Tracks Cyclin B. Maps to SBML symbol `cycb`.'),
        'cdk1': ('cdk1', 'native SBML value', 'Tracks CDK1. Maps to SBML symbol `cdk1`.'),
        'icycb_cdk1_cyto': ('icycb_cdk1_cyto', 'native SBML value', 'Tracks Icycb CDK1 Cyto. Maps to SBML symbol `icycb_cdk1_cyto`.'),
        'p21_acycb_cdk1_nuc': ('p21_acycb_cdk1_nuc', 'native SBML value', 'Tracks P21 Acycb CDK1 Nuc. Maps to SBML symbol `p21_acycb_cdk1_nuc`.'),
        'icycb_cdk1_nuc': ('icycb_cdk1_nuc', 'native SBML value', 'Tracks Icycb CDK1 Nuc. Maps to SBML symbol `icycb_cdk1_nuc`.'),
        'inactive_apc_c_c_cdc20': ('iAPC_Cdc20', 'native SBML value', 'Tracks Inactive APC/C/C Cdc20. Maps to SBML symbol `iAPC_Cdc20`.'),
        'inactive_apc_c_c_cdh1': ('iAPC_Cdh1', 'native SBML value', 'Tracks Inactive APC/C/C Cdh1. Maps to SBML symbol `iAPC_Cdh1`.'),
        'phosphorylated_rb_ppp_copy': ('pRbPPP_copy', 'native SBML value', 'Tracks Phosphorylated Rb PPP Copy. Maps to SBML symbol `pRbPPP_copy`.'),
    }

    def __init__(self, model_path: str = 'data/MODEL1812130001.xml', integration_step: float = 0.01) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)

    def inputs(self):
        specs = super().inputs()
        specs.pop("integration_step", None)
        return specs


# Canonical alias for stable entrypoint naming.
Abroudi2017MammalianCellCycleControlModelModel1812130001Model = SbmlAbroudi2017MammalianCellCycleControlModel
